name: lucide_icons_flutter_dense
description: A denser-weight Lucide icon library package for Flutter applications with 0.25 stroke-width steps from 0.5 to 3.0.
version: 3.1.14+2-dense.1
homepage: https://lucide.dev
repository: https://github.com/hashencode/lucide_icons_flutter_dense

environment:
  sdk: ^3.0.0
  # flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  recase: ^4.1.0
  lint: ^2.8.0

flutter:
  fonts:
    - family: Lucide
      fonts:
        - asset: assets/lucide.ttf
    - family: Lucide100
      fonts:
        - asset: assets/build_font/LucideVariable-w100.ttf
          weight: 100
    - family: Lucide150
      fonts:
        - asset: assets/build_font/LucideVariable-w150.ttf
    - family: Lucide200
      fonts:
        - asset: assets/build_font/LucideVariable-w200.ttf
          weight: 200
    - family: Lucide250
      fonts:
        - asset: assets/build_font/LucideVariable-w250.ttf
    - family: Lucide300
      fonts:
        - asset: assets/build_font/LucideVariable-w300.ttf
          weight: 300
    - family: Lucide350
      fonts:
        - asset: assets/build_font/LucideVariable-w350.ttf
    - family: Lucide400
      fonts:
        - asset: assets/build_font/LucideVariable-w400.ttf
          weight: 400
    - family: Lucide450
      fonts:
        - asset: assets/build_font/LucideVariable-w450.ttf
    - family: Lucide500
      fonts:
        - asset: assets/build_font/LucideVariable-w500.ttf
          weight: 500
    - family: Lucide550
      fonts:
        - asset: assets/build_font/LucideVariable-w550.ttf
    - family: Lucide600
      fonts:
        - asset: assets/build_font/LucideVariable-w600.ttf
          weight: 600
    # - family: Lucide700
    #   fonts:
    #     - asset: assets/build_font/LucideVariable-w700.ttf
    #       weight: 700
# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

screenshots:
  - description: Lucide Logo
    path: screenshots/logo.png

topics:
  - lucide
  - lucide-icons
  - feather
  - feather-icons
  - icons
