import 'dart:convert';
import "dart:io";

import 'package:recase/recase.dart';

const String kPackageName = 'lucide_icons_flutter_dense';
const List<int> kWeightTokens = <int>[
  100,
  150,
  200,
  250,
  300,
  350,
  400,
  450,
  500,
  550,
  600,
];
const String kLucideSourcePath = 'lucide/lucide-source';

void main(List<String> args) {
  File fontsPreviewFile = File(args[0]);

  if (!fontsPreviewFile.existsSync()) {
    print('lucide preview file not found');
    exit(0);
  }

  String content = fontsPreviewFile.readAsStringSync();

  Map<String, dynamic> jsonMap = json.decode(content);
  Map<String, Map<String, String>> result = {};

  jsonMap.forEach((key, value) {
    if (value is Map<String, String>) {
      result[key] = Map<String, String>.from(value);
    }
  });

  List<Map<dynamic, dynamic>> resultList = jsonMap.entries
      .map((entry) => {'name': entry.key, ...entry.value})
      .toList();
  // stdout.write("info message1 ${resultList}");
  // final c = parse(content);
  // final list = c.getElementsByClassName('glyph');

  List<String> generatedOutput = [
    "library lucide_icons;\n",
    "import \"package:flutter/widgets.dart\";\n",
    "\n",
    "// THIS FILE IS AUTOMATICALLY GENERATED!\n\n",
    "/// Lucide Icons\n",
    "class LucideIcons {\n",
    "/// Private constructor to prevent instantiation.\n",
    "/// This class is intended solely for organizing static icon definitions.\n",
    "/// Making the constructor private stops the IDE from suggesting object creation.\n",
    "const LucideIcons._();\n\n",
  ];
  List<String> listIconTest = [
    "\nimport 'package:flutter/material.dart';",
    "\nimport 'package:$kPackageName/lucide_icons.dart';",
    "\n/// Lucide Icons",
    "\nconst List<IconData> icons = [",
  ];
  List<String> listIconNamesTest = ["\n\nconst List<String> iconNames = ["];
  final generatedIconNames = <String>{};
  final svgAliases = buildSvgAliases(Directory(kLucideSourcePath));

  for (Map data in resultList) {
    String iconName = data['name'];
    final baseName = ReCase(iconName).camelCase;
    final codePoint = parseUnicodeString(data['unicode']);

    if (!generatedIconNames.add(baseName)) {
      print('Bỏ qua icon trùng tên Dart: $iconName -> $baseName');
      continue;
    }

    final svgContent = readSvgPreviewBase64(
      iconName: iconName,
      sourceDir: Directory(kLucideSourcePath),
      aliases: svgAliases,
    );

    generatedOutput.add(
      "/// ${data['name']}\n"
      "${buildPreviewMarkdown(data['name'], svgContent)}"
      "static const IconData $baseName = const IconData($codePoint, fontFamily: 'Lucide', fontPackage: '$kPackageName');\n"
      "static const IconData ${baseName}Dir = const IconData($codePoint, fontFamily: 'Lucide', fontPackage: '$kPackageName', matchTextDirection: true);\n",
    );
    listIconTest.add("\nLucideIcons.$baseName,");
    listIconNamesTest.add("\n'$baseName',");

    // Sinh thêm các biến với fontFamily Lucide100...Lucide600 và các mốc trung gian
    for (final int i in kWeightTokens) {
      final svgContent = readSvgPreviewBase64(
        iconName: iconName,
        sourceDir: Directory('lucide/svg_input/weight$i'),
        aliases: svgAliases,
      );

      String fontFamily = 'Lucide$i';
      String varName = '$baseName$i';
      generatedOutput.add(
        "/// ${data['name']} với fontFamily $fontFamily\n"
        "${buildPreviewMarkdown(data['name'], svgContent)}"
        "static const IconData $varName = const IconData($codePoint, fontFamily: '$fontFamily', fontPackage: '$kPackageName');\n",
      );
      listIconTest.add("\nLucideIcons.$varName,");
      listIconNamesTest.add("\n'$varName',");
    }
  }
  // print('$val $name');
  // }

  generatedOutput.add("}\n");
  listIconTest.add("];");
  listIconNamesTest.add("];");
  //  stdout.write("info message2 ${generatedOutput}");

  File output = File('../lib/lucide_icons.dart');
  output.writeAsStringSync(generatedOutput.join());
  File outputTest = File('../lib/test_icons.dart');
  outputTest.writeAsStringSync(listIconTest.join() + listIconNamesTest.join());
}

Map<String, String> buildSvgAliases(Directory sourceDir) {
  final aliases = <String, String>{};

  if (!sourceDir.existsSync()) {
    return aliases;
  }

  for (final entity in sourceDir.listSync()) {
    if (entity is! File || !entity.path.endsWith('.json')) {
      continue;
    }

    try {
      final metadata = json.decode(entity.readAsStringSync());
      if (metadata is! Map<String, dynamic>) {
        continue;
      }

      final canonicalName = fileStem(entity);
      final metadataAliases = metadata['aliases'];
      if (metadataAliases is! List) {
        continue;
      }

      for (final alias in metadataAliases) {
        final aliasName = switch (alias) {
          String value => value,
          Map<String, dynamic> value when value['name'] is String =>
            value['name'] as String,
          _ => null,
        };

        if (aliasName == null || aliasName.isEmpty) {
          continue;
        }

        aliases.putIfAbsent(aliasName, () => canonicalName);
      }
    } catch (e) {
      stderr.writeln('Could not read Lucide metadata ${entity.path}: $e');
    }
  }

  return aliases;
}

String readSvgPreviewBase64({
  required String iconName,
  required Directory sourceDir,
  required Map<String, String> aliases,
}) {
  final svgFile = resolveSvgFile(
    iconName: iconName,
    sourceDir: sourceDir,
    aliases: aliases,
  );

  if (svgFile == null) {
    stderr.writeln('SVG preview not found for $iconName');
    return '';
  }

  try {
    return base64Encode(utf8.encode(normalizeSvgPreview(svgFile)));
  } catch (e) {
    stderr.writeln('Could not read SVG preview for $iconName: $e');
    return '';
  }
}

File? resolveSvgFile({
  required String iconName,
  required Directory sourceDir,
  required Map<String, String> aliases,
}) {
  final normalizedName = iconName.replaceFirst('icon-', '');
  final exactFile = File('${sourceDir.path}/$normalizedName.svg');
  if (exactFile.existsSync()) {
    return exactFile;
  }

  final canonicalName = aliases[normalizedName];
  if (canonicalName == null) {
    return null;
  }

  final aliasFile = File('${sourceDir.path}/$canonicalName.svg');
  if (aliasFile.existsSync()) {
    return aliasFile;
  }

  return null;
}

String normalizeSvgPreview(File svgFile) {
  var svgContent = svgFile.readAsStringSync();

  svgContent = svgContent
      .replaceAll('stroke="currentColor"', 'stroke="#0066cc"')
      .replaceAll('width="24"', 'width="48"')
      .replaceAll('height="24"', 'height="48"');

  if (!svgContent.contains('xmlns="http://www.w3.org/2000/svg"')) {
    svgContent = svgContent.replaceFirst(
      '<svg',
      '<svg xmlns="http://www.w3.org/2000/svg"',
    );
  }

  if (!RegExp(r'<svg[^>]*\sversion=').hasMatch(svgContent)) {
    svgContent = svgContent.replaceFirst('<svg', '<svg version="1.1"');
  }

  return svgContent;
}

String buildPreviewMarkdown(String iconName, String base64Svg) {
  if (base64Svg.isEmpty) {
    return '';
  }

  return '/// ![$iconName](data:image/svg+xml;base64,$base64Svg)\n';
}

String fileStem(File file) {
  final path = file.path;
  final fileName = path.split(Platform.pathSeparator).last;
  final dotIndex = fileName.lastIndexOf('.');

  if (dotIndex == -1) {
    return fileName;
  }

  return fileName.substring(0, dotIndex);
}

int parseUnicodeString(String unicodeString) {
  // Remove the '&#' prefix and ';' suffix from the string
  String hexString = unicodeString.substring(2, unicodeString.length - 1);

  // Parse the hexadecimal string and convert it to an integer
  int unicodeInt = int.parse(hexString);

  return unicodeInt;
}

int parseUnicodeString2(String unicodeString) {
  // Remove the '\\' prefix from the string
  String hexString = unicodeString.substring(2);

  // Parse the hexadecimal string and convert it to an integer
  int unicodeInt = int.parse(hexString, radix: 16);

  return unicodeInt;
}
